import express from "express";
import userRouter from "../modules/user/routes/user.routes.js";
import authRouter from "../modules/auth/routes/auth.routes.js";
import cartRouter from "../modules/cart/routers/cart.routes.js";
import brandRouter from "../modules/product/routes/brand.routes.js";
import coupounRouter from "../modules/coupon/routers/cupon.routes.js";
import productRouter from "../modules/product/routes/product.routes.js";
import categoryRouter from "../modules/product/routes/category.routes.js";
import subCategoryRouter from "../modules/product/routes/subCategory.routes.js";

const router = express.Router();
router.use("/auth", authRouter);
router.use("/user", userRouter);
router.use("/cart", cartRouter);
router.use("/brand", brandRouter);
router.use("/product", productRouter);
router.use("/coupon", coupounRouter);
router.use("/category", categoryRouter);
router.use("/subcategory", subCategoryRouter);
export default router;
